<a href="https://colab.research.google.com/github/WalidYaser/Deep-Learning/blob/main/RNN_back_propagatio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Initialize Matrices based on the numerical example
W_X = np.array([
    [0.6, 0.8, 0.4, 0.8],
    [0.2, 0.2, 0.8, 0.7],
    [0.9, 0.8, 0.1, 0.2]
])

W_H = np.array([
    [0.1, 0.5, 0.1],
    [0.5, 0.9, 0.3],
    [0.3, 0.2, 0.1]
])

W_Y = np.array([
    [0.9, 0.8, 0.3],
    [0.2, 0.3, 0.4],
    [0.6, 0.9, 0.1],
    [0.5, 0.0, 0.3]
])

# Inputs at t=1
H_prev = np.array([[0], [0], [0]]) # H_{t-1}
X_1 = np.array([[1], [0], [0], [0]]) # X_i

# Assuming the target "correct" class is the first one (index 0)
Y_target = np.array([[1], [0], [0], [0]])

# Define Activation Functions
def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1.0 - np.tanh(x)**2

def softmax(x):
    exp_x = np.exp(x - np.max(x)) # Subtract max for numerical stability
    return exp_x / exp_x.sum(axis=0)

# ==========================================
# FORWARD PROPAGATION
# ==========================================
print("--- FORWARD PROPAGATION ---")

# Calculate hidden nodes (a1)
a_1 = np.dot(W_H, H_prev) + np.dot(W_X, X_1)
print(f"a1:\n{a_1}\n")

# Apply activation function (h1)
h_1 = tanh(a_1)
print(f"h1 (rounded):\n{np.round(h_1, 2)}\n")

# Calculate output (y1)
y_raw = np.dot(W_Y, h_1)
y_1 = softmax(y_raw)
print(f"y1 (Prediction):\n{np.round(y_1, 2)}\n")

# Calculate Loss (Square Error: E = (y_hat - y)^2 )
loss = np.sum((y_1 - Y_target)**2)
print(f"Loss (Square Error): {round(loss, 4)}\n")


# ==========================================
# BACKPROPAGATION THROUGH TIME (Single Step)
# ==========================================
print("--- BACKPROPAGATION ---")

# 1. Gradient of Loss with respect to output (y_hat - y)
dY = y_1 - Y_target

# 2. Adjust Output Weights (W_Y)
# Formula: dE/dW_Y = dY * h_1.T
dW_Y = np.dot(dY, h_1.T)
print(f"Gradient for W_Y (dW_Y):\n{np.round(dW_Y, 4)}\n")

# 3. Propagate error back to hidden state
dh_1 = np.dot(W_Y.T, dY)

# 4. Derivative of tanh activation
da_1 = dh_1 * tanh_derivative(a_1)

# 5. Adjust Hidden Weights (W_H)
# Formula: dE/dW_H = da_1 * H_prev.T
dW_H = np.dot(da_1, H_prev.T)
print(f"Gradient for W_H (dW_H):\n{np.round(dW_H, 4)}\n")

# 6. Adjust Input Weights (W_X)
# Formula: dE/dW_X = da_1 * X_1.T
dW_X = np.dot(da_1, X_1.T)
print(f"Gradient for W_X (dW_X):\n{np.round(dW_X, 4)}\n")

# 7. Update Weights (Assuming a learning rate of 0.01)
learning_rate = 0.01
W_Y_updated = W_Y - (learning_rate * dW_Y)
W_H_updated = W_H - (learning_rate * dW_H)
W_X_updated = W_X - (learning_rate * dW_X)

print("Weights have been successfully updated using gradients!")

--- FORWARD PROPAGATION ---
a1:
[[0.6]
 [0.2]
 [0.9]]

h1 (rounded):
[[0.54]
 [0.2 ]
 [0.72]]

y1 (Prediction):
[[0.32]
 [0.21]
 [0.24]
 [0.22]]

Loss (Square Error): 0.614

--- BACKPROPAGATION ---
Gradient for W_Y (dW_Y):
[[-0.3643 -0.1339 -0.4859]
 [ 0.1154  0.0424  0.154 ]
 [ 0.1299  0.0478  0.1733]
 [ 0.119   0.0437  0.1587]]

Gradient for W_H (dW_H):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Gradient for W_X (dW_X):
[[-0.2218  0.      0.      0.    ]
 [-0.2504  0.      0.      0.    ]
 [-0.0131  0.      0.      0.    ]]

Weights have been successfully updated using gradients!
